### ISSUE TITLE
HTTP Basic authentication not working

### ISSUE THREAD

**Issue by MitulShah1** [confluentinc/cp-demo#132]
Hello I've added below environment variable to docker-composer yml

 CONTROL_CENTER_REST_AUTHENTICATION_METHOD: 'BASIC'      
 CONTROL_CENTER_REST_REALM: 'c3'
 CONTROL_CENTER_REST_AUTHENTICATION_ROLES: 'Administrators,Restricted'
 CONTROL_CENTER_REST_RESTRICTED_ROLES: 'Restricted'
 CONTROL_CENTER_OPTS: -Djava.security.auth.login.config=/etc/confluent-control-center/propertyfile.conf

and then when i am running https://docs.confluent.io/current/security/basic-auth.html#kconnect-rest-api given command it gives error 
"/tmp/confluent/login.properties: No such file or directory" 

it will be appreciate to provide http basic authentication configuration on github cp-demo as well.

Thanks.

**Comment by MosheBlumbergX** [comment]
When you start Control Center, make sure you have the followings, the `/tmp/confluent/login.properties` sounds like you're trying to pass your local /tmp to the container, please try to put it in a location that is exposed to the container, like the `scripts/security/`in this repo. 

```
      CONTROL_CENTER_REST_AUTHENTICATION_METHOD: BASIC
      CONTROL_CENTER_REST_AUTHENTICATION_REALM: c3
      CONTROL_CENTER_REST_AUTHENTICATION_ROLES: Administrators,Restricted
      CONTROL_CENTER_AUTH_RESTRICTED_ROLES: Restricted
      CONTROL_CENTER_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/propertyfile.jaas
```
/etc/kafka/secrets/propertyfile.jaas
```
c3 {
  org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
  file="/etc/kafka/secrets/login.properties";
};
```

/etc/kafka/secrets/login.properties:
```
admin: admin_pw,Administrators
disallowed: no_access
restricted: restricted_pw,Restricted
```

**Comment by MitulShah1** [comment]
@MosheBlumbergX  thanks working fine

**Comment by Naveenreddybv** [comment]
Hello, I tried to set up a username and password for the control center, I followed the above steps, but it gave error. 
ERROR: Unable to obtain lock as state directory is already locked by another process.
Caused by: Unable to initialize state, this can happen if multiple instances of Kafka streams are Running in the same directory.

Please help to resolve this issue. Thank you 
![error](https://user-images.githubusercontent.com/97667884/149308713-24da4b99-6e2e-4aed-b7b5-8d6f2a27fb32.jpeg)
